version: 2
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          command: |
            cd app
            make e2e

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
