version: '3.2'
services:
  app:
    environment:
      - REACT_APP_API_URL=http://api:8080
  cypress:
    image: 'cypress/included:3.2.0'
    depends_on:
      - app
    entrypoint: /scripts/wait_for_it.sh app:3000 -- cypress run
    environment:
      - CYPRESS_baseUrl=http://app:3000
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
      - ./scripts:/scripts
