version: '3.2'
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      # share everything BUT node_modules from the host
      - .:/app
      - /app/node_modules
    depends_on:
      - api
  api:
    build:
      context: ../api
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      # share everything BUT node_modules from the host
      - ../api:/api
      - /api/node_modules
